-- 1. SAVED ESTIMATES TABLE
create table saved_estimates (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  locality text not null,
  property_type text not null, -- 'Land' or 'House'
  estimated_price text not null, -- e.g. "₹15-20 Lakhs"
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table saved_estimates enable row level security;

-- Policies
create policy "Users can view their own saved estimates"
  on saved_estimates for select
  using ( auth.uid() = user_id );

create policy "Users can insert their own saved estimates"
  on saved_estimates for insert
  with check ( auth.uid() = user_id );

create policy "Users can delete their own saved estimates"
  on saved_estimates for delete
  using ( auth.uid() = user_id );

-- 2. LEADS TABLE
create table leads (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users, -- Optional, can be anonymous
  phone_number text not null,
  interest_area text not null, -- e.g. "Buying in Kowdiar"
  status text default 'New', -- 'New', 'Contacted', 'Closed'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table leads enable row level security;

-- Policies
-- Users can insert leads (anyone can submit a lead)
create policy "Anyone can insert leads"
  on leads for insert
  with check ( true );

-- Only admins/service role can view leads (Users shouldn't see other leads)
-- No select policy for public means it's private by default.

-- 3. LOCALITY SEARCH HISTORY TABLE (for baselines)
create table locality_search_history (
  id bigint generated by default as identity primary key,
  locality text not null,
  land_rate numeric not null, -- in Lakhs per cent
  search_date date not null default current_date,
  source_quality text default 'medium', -- 'high' = actual listing, 'medium' = article
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Index for fast baseline queries
create index idx_locality_search on locality_search_history(locality, search_date desc);

-- Enable RLS (no user-specific policies needed - this is anonymous data)
alter table locality_search_history enable row level security;

-- Anyone can insert search results (anonymous)
create policy "Anyone can insert search history"
  on locality_search_history for insert
  with check ( true );

-- Anyone can view search history (for baseline calculations)
create policy "Anyone can view search history"
  on locality_search_history for select
  using ( true );

-- 4. LOCALITY BASELINES VIEW (auto-calculated)
create view locality_baselines as
select 
  locality,
  percentile_cont(0.5) within group (order by land_rate) as median_rate,
  count(*) as sample_size,
  max(search_date) as last_updated,
  stddev(land_rate) as std_deviation
from locality_search_history
where search_date > current_date - 90  -- Last 90 days only
group by locality
having count(*) >= 1;  -- At least 1 sample

-- 5. SEARCH CACHE TABLE (24-hour caching)
create table search_cache (
  id bigint generated by default as identity primary key,
  locality text not null unique,
  cached_rate numeric not null,
  cached_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Index for fast cache lookups
create index idx_cache_locality on search_cache(locality);

-- Anyone can read/write cache
alter table search_cache enable row level security;

create policy "Anyone can use search cache"
  on search_cache for all
  using ( true )
  with check ( true );
