-- 1. SAVED ESTIMATES TABLE
create table saved_estimates (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  locality text not null,
  property_type text not null, -- 'Land' or 'House'
  estimated_price text not null, -- e.g. "₹15-20 Lakhs"
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
-- Enable RLS
alter table saved_estimates enable row level security;
-- Policies
create policy "Users can view their own saved estimates"
  on saved_estimates for select
  using ( auth.uid() = user_id );
create policy "Users can insert their own saved estimates"
  on saved_estimates for insert
  with check ( auth.uid() = user_id );
create policy "Users can delete their own saved estimates"
  on saved_estimates for delete
  using ( auth.uid() = user_id );
-- 2. LEADS TABLE
create table leads (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users, -- Optional, can be anonymous
  phone_number text not null,
  interest_area text not null, -- e.g. "Buying in Kowdiar"
  status text default 'New', -- 'New', 'Contacted', 'Closed'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
-- Enable RLS
alter table leads enable row level security;
-- Policies
-- Users can insert leads (anyone can submit a lead)
create policy "Anyone can insert leads"
  on leads for insert
  with check ( true );
-- Only admins/service role can view leads (Users shouldn't see other leads)
-- No select policy for public means it's private by default.
